sudo: false
dist: trusty
language: java
jdk:
  - oraclejdk8
services:
  - docker
cache:
  directories:
    - "$HOME/.cache"
before_install:
  - cp ./.mvn/ci-settings.xml $HOME/.m2/settings.xml
  - export VERSIONING_GIT_TAG=$TRAVIS_TAG;
  - export VERSIONING_GIT_BRANCH=$TRAVIS_BRANCH;
script:
  - "mvn -P ci install"

deploy:
  - provider: script
    script: "mvn -P ci deploy -DskipTests -Dversioning.disable=false"
    skip_cleanup: false
    on:
      branch: master
  - provider: script
    script: "mvn -P ci deploy -DskipTests -Dversioning.disable=false"
    skip_cleanup: false
    on:
      tags: true
