sudo: false
dist: trusty
language: java
jdk:
  - oraclejdk8
services:
  - docker
cache:
  directories:
    - "$HOME/.cache"
before_install:
  - cp ./.mvn/ci-settings.xml $HOME/.m2/settings.xml

script:
  - "mvn -P ci install"

deploy:
  provider: script
  script: "mvn -P ci deploy -DskipTests -s ./.mvn/ci_settings.xml"
  skip_cleanup: false
  on:
    tags: true
    branch: master
