sudo: false
dist: trusty
language: java
jdk:
  - oraclejdk8
services:
  - docker
cache:
  directories:
    - "$HOME/.cache"
before_install:
  - cp ./.mvn/ci-settings.xml $HOME/.m2/settings.xml
  - export VERSIONING_GIT_TAG=$TRAVIS_TAG;
  - export VERSIONING_GIT_BRANCH=$TRAVIS_BRANCH;
  - wget -P $HOME https://downloads.apache.org/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
  - tar xzvf $HOME/apache-maven-3.6.3-bin.tar.gz -C $HOME
  - ls -al $HOME
  - ls -al $HOME/apache-maven-3.6.3/
  - ls -al $HOME/apache-maven-3.6.3/bin
  - pwd
  - export PATH=$HOME/apache-maven-3.6.3/bin:$PATH
  - $HOME/apache-maven-3.6.3/bin/mvn -v
script:
  - "$HOME/apache-maven-3.6.3/bin/mvn -P ci install -Dversioning.disable=false"

deploy:
  - provider: script
    script: "$HOME/apache-maven-3.6.3/bin/mvn -P ci deploy -DskipTests -Dversioning.disable=false"
    skip_cleanup: false
    on:
      condition: "$TRAVIS_TAG = ^v.*$ OR $TRAVIS_BRANCH = master"
